export const s = {
  section: { marginBottom: 40 },
  sectionTitle: { color: '#ffc107', fontSize: 22, marginBottom: 24, borderBottom: '1px solid #334155', paddingBottom: 12 },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 32 },
  formCol: { display: 'flex', flexDirection: 'column', gap: 14 },
  previewCol: { display: 'flex', flexDirection: 'column', gap: 12 },
  label: { color: '#94a3b8', fontSize: 13, marginBottom: 2 },
  input: { padding: '10px 14px', borderRadius: 8, border: '1px solid #334155', background: '#0f172a', color: '#fff', fontSize: 14, outline: 'none', textAlign: 'right' },
  textarea: { padding: '10px 14px', borderRadius: 8, border: '1px solid #334155', background: '#0f172a', color: '#fff', fontSize: 14, outline: 'none', textAlign: 'right', resize: 'vertical', fontFamily: 'inherit' },
  fileInput: { color: '#94a3b8', fontSize: 13 },
  saveBtn: { padding: '12px 24px', background: '#ffc107', color: '#000', border: 'none', borderRadius: 10, fontWeight: 'bold', fontSize: 15, cursor: 'pointer', marginTop: 8 },
  previewImg: { width: '100%', maxHeight: 220, objectFit: 'cover', borderRadius: 12, border: '1px solid #334155' },
  previewBox: { background: '#0f172a', borderRadius: 12, padding: 16 },
  previewBtn: { display: 'inline-block', marginTop: 10, padding: '8px 20px', background: '#ffc107', color: '#000', borderRadius: 20, fontWeight: 'bold', fontSize: 13 },
  card: { background: '#1e293b', borderRadius: 14, overflow: 'hidden', border: '1px solid #334155' },
  cardImg: { width: '100%', height: 160, objectFit: 'cover' },
  cardBody: { padding: 16 },
  cardTitle: { color: '#fff', fontWeight: 'bold', fontSize: 15, marginBottom: 6 },
  cardDesc: { color: '#94a3b8', fontSize: 13, marginBottom: 10, lineHeight: 1.6 },
  badge: { display: 'inline-block', padding: '4px 12px', background: '#ffc107', color: '#000', borderRadius: 20, fontSize: 12, fontWeight: 'bold' },
  cardActions: { display: 'flex', gap: 8, marginTop: 12 },
  editBtn: { flex: 1, padding: '8px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 13 },
  deleteBtn: { flex: 1, padding: '8px', background: '#ef4444', color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 13 },
  addBtn: { padding: '12px 28px', background: '#22c55e', color: '#fff', border: 'none', borderRadius: 10, fontWeight: 'bold', fontSize: 15, cursor: 'pointer', marginBottom: 24 },
  grid3: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 20 },
  modal: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: 20 },
  modalBox: { background: '#1e293b', borderRadius: 16, padding: 32, width: '100%', maxWidth: 500, display: 'flex', flexDirection: 'column', gap: 14, direction: 'rtl', maxHeight: '90vh', overflowY: 'auto' },
  modalTitle: { color: '#ffc107', fontSize: 20, marginBottom: 8 },
  cancelBtn: { padding: '12px', background: '#334155', color: '#fff', border: 'none', borderRadius: 10, fontWeight: 'bold', fontSize: 15, cursor: 'pointer' },
};
